### PR TITLE
Adding Rest Service for Member

### PR DESCRIPTION
**Pull request by justhardinal**
i build for :
-MemberEntity
-MemberController
-MemberDao
-member table schema

would you check that all i write that code?

### CODE REVIEW

**Comment by xkillx** [comment]
When I running this, i've got
```java
Caused by: org.hibernate.AnnotationException: Unknown Id.generator: system-uuid
	at org.hibernate.cfg.BinderHelper.makeIdGenerator(BinderHelper.java:640)
	at org.hibernate.cfg.AnnotationBinder.processId(AnnotationBinder.java:2362)
	at org.hibernate.cfg.AnnotationBinder.processElementAnnotations(AnnotationBinder.java:2268)
	at org.hibernate.cfg.AnnotationBinder.processIdPropertiesIfNotAlready(AnnotationBinder.java:963)
	at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:796)
	at org.hibernate.cfg.Configuration$MetadataSourceQueue.processAnnotatedClassesQueue(Configuration.java:3845)
	at org.hibernate.cfg.Configuration$MetadataSourceQueue.processMetadata(Configuration.java:3799)
	at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1412)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:852)
```

**Comment by justhardinal** [comment]
uumm i already put that code in my fork of bpustaka 
would u check it in : https://github.com/BelajarJavaBareng/bpustaka/compare/master...justhardinal:master

**Comment by xkillx** [comment]
Yes i already checked that, and test in my IDE using Spring STS, but when I run this I got,

```java
Caused by: org.hibernate.AnnotationException: Unknown Id.generator: system-uuid
	at org.hibernate.cfg.BinderHelper.makeIdGenerator(BinderHelper.java:640)
	at org.hibernate.cfg.AnnotationBinder.processId(AnnotationBinder.java:2362)
	at org.hibernate.cfg.AnnotationBinder.processElementAnnotations(AnnotationBinder.java:2268)
	at org.hibernate.cfg.AnnotationBinder.processIdPropertiesIfNotAlready(AnnotationBinder.java:963)
	at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:796)
	at org.hibernate.cfg.Configuration$MetadataSourceQueue.processAnnotatedClassesQueue(Configuration.java:3845)
	at org.hibernate.cfg.Configuration$MetadataSourceQueue.processMetadata(Configuration.java:3799)
	at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1412)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:852)
	... 23 more
```

**Comment by xkillx** [comment]
In your code:

```java
@Id
@GeneratedValue(generator = "system-uuid")
private String id;
```

In Mr.Endy code:
```java
@Id 
@GeneratedValue(generator = "system-uuid")
@GenericGenerator(name = "system-uuid", strategy = "uuid")
private String id;
```

I think that is the problem,

**Comment by xkillx** [comment]
I try to fix that code, and already push [member branch](https://github.com/xkillx/bpustaka/tree/member) in my repository, based on your work.

**Comment by endymuhardin** [comment]
Duplicate with 52

**Pull request closed without merging**
